### ISSUE TITLE
ReaperScans, issue getting chapter list for large series.

### ISSUE THREAD

**Issue by RedSquirrel87** [RedSquirrel87/manga-downloader#768]
**[Original report](https://bitbucket.org/Red_Squirrel/manga-downloader/issues/768) by Anonymous.**

----------------------------------------

Application is returning an error when trying to get the chapter list for larger series, this one for example doesn’t work;
https://reaperscans.com/comics/4921-demonic-emperor

Whereas this one dose;
https://reaperscans.com/comics/4364-estio

**Comment by RedSquirrel87** [comment]
v60 released, it should fix this issue

**Comment by Steven-OConnell** [comment]
ReaperScans is still broken, the logs still show a 429 error.

`[Wed May 10 15:02:19 CST 2023] Loading manga from https://reaperscans.com/comics/4921-demonic-emperor
[Wed May 10 15:02:35 CST 2023] HTTP response code: 200
[Wed May 10 15:02:35 CST 2023] Framework: REAPERSCANS
[Wed May 10 15:02:43 CST 2023] HTTP response code: 429
[Wed May 10 15:02:43 CST 2023] Error: NULL HTML code (-2).
[Wed May 10 15:02:43 CST 2023] Error while getting chapters list:
java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
	at java.base/java.io.StringReader.<init>(StringReader.java:51)
	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
	at mainpackage.ReaperScans.GetChapters(ReaperScans.java:150)
	at mainpackage.NewJFrame.GetChaptersList(NewJFrame.java:8941)
	at mainpackage.NewJFrame.access$22000(NewJFrame.java:164)
	at mainpackage.NewJFrame$201.run(NewJFrame.java:9316)
	at java.base/java.lang.Thread.run(Thread.java:833)
[Wed May 10 15:02:43 CST 2023] Error: NULL chapters list.`

I also tried this with a VPN to make sure my IP wasn't getting blocked either.

**Comment by RedSquirrel87** [comment]
v60.1 just released, I increased the waiting time to a random value from 1 to 2 seconds.
Please let me know if now it works for you too

**Comment by Steven-OConnell** [comment]
I just confirmed that it is working now.
Thanks a lot for the fix.
As a side note: Both HakuNeko & HDoujin Downloader have the same problem, so you're basically the only one who's got this working correctly. XD

**Comment by RedSquirrel87** [comment]
I just released a new update (v60.2) that should fix the 403 error, please let me know if it works now 👍🏻
P.s.: I'm

**Comment by Steven-OConnell** [comment]
Alright awesome, it is working.
I checked the downloaded content and it's all there.
Thanks a lot. :)
