### ISSUE TITLE
ERROR on Manga Title from Certain webtoons.com titles

### ISSUE THREAD

**Issue by valdearg** [RedSquirrel87/manga-downloader#877]
Noticed that when scanning a couple of titles, the manga name fails to come through and it's replaced with ERROR.

![image](https://github.com/user-attachments/assets/5a522939-91e3-4083-bc84-6a2601617421)

https://www.webtoons.com/en/canvas/gl-us-right-now/list?title_no=125282
https://www.webtoons.com/en/canvas/shes-into-me/list?title_no=920794

Couple of working ones are 
https://www.webtoons.com/en/fantasy/tower-of-god/list?title_no=95

```
[Wed Jan 01 00:43:57 GMT 2025] Program started.
[Wed Jan 01 00:43:57 GMT 2025] MangaDownloader v70.1
[Wed Jan 01 00:43:57 GMT 2025] OS: Windows 11 (amd64) | JVM: 1.8.0_421
java.io.FileNotFoundException: jobs.dat (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at mainpackage.NewJFrame.LoadJobsList(NewJFrame.java:6993)
	at mainpackage.NewJFrame$236.run(NewJFrame.java:11136)
	at java.lang.Thread.run(Unknown Source)
[Wed Jan 01 00:43:59 GMT 2025] [DB] Database current version: 5
[Wed Jan 01 00:44:12 GMT 2025] Database backup created successfully!
[Wed Jan 01 00:51:06 GMT 2025] Loading manga from https://www.webtoons.com/en/canvas/shes-into-me/list?title_no=920794
[Wed Jan 01 00:51:06 GMT 2025] HTTP response code: 200
[Wed Jan 01 00:51:06 GMT 2025] Framework: WEBTOONS
[Wed Jan 01 00:51:29 GMT 2025] 86 chapters found.
```

**Comment by RedSquirrel87** [comment]
Thank you for reporting the issue, surely they have changed something in their html code that broke the title acquisition, I'll fix this asap

**Comment by RedSquirrel87** [comment]
v70.2 released, it should fix this issue 👍

**Comment by valdearg** [comment]
Thanks! That works perfectly!

**Comment by HikariGo** [comment]
Not fixed unfortunately.

Have not replicated the error exactly, but have a number of examples where Webtoon titles are not being parsed correctly.

i.e.

https://www.webtoons.com/en/romance/answer-me-my-prince/list?title_no=4672

Based on my filename naming scheme should be: Answer Me, My Prince

Instead I get: Answer Me, My Prince My Gently Raised Beast The First Night With the Duke

It seems to be parsing the names of additional Webtoon titles and adding them into filename as the title

Some other titles where this issue is replicated (there are more):
- https://www.webtoons.com/en/romance/a-heart-for-the-emperor/list?title_no=4269
- https://www.webtoons.com/en/romance/cierra/list?title_no=3670
- https://www.webtoons.com/en/comedy/everywhere-and-nowhere/list?title_no=1598

Does not happen on all ones I have tried though, with filenames parsing properly for ones such as:
- https://www.webtoons.com/en/drama/agatha/list?title_no=3525
- https://www.webtoons.com/en/fantasy/how-to-survive-a-romance-fantasy/list?title_no=2855
- https://www.webtoons.com/en/romance/marry-me/list?title_no=1951

App/Device details from JVM log:
MangaDownloader v70.2
OS: Mac OS X (aarch64) | JVM: 23
Patreon status: no linked Patreon account.
[DB] Database current version: 5

**Comment by RedSquirrel87** [comment]
I already fixed this new issue with v70.3 👍
